all: task1_sp task1_mp task2

task1_sp:
	g++ -std=c++0x task1_sp.cpp -o task1_sp.out -lvg
task1_mp:
	g++ -std=c++0x task1_mps.cpp -o task1_mps.out -lvg
	g++ -std=c++0x task1_mpr.cpp -o task1_mpr.out -lvg

task2:
	g++ -std=c++0x task2.cpp -o task2.out -lvg
